package it.unicam.IDS.progetto.Entita;

public enum Ruoli {

    ROLE_GESTOREPIATTAFORMA,
    ROLE_CURATORI,
    ROLE_CONTRIBUTORIAUTORIZZATI,
    ROLE_ANIMATORI,
    ROLE_CONTRIBUTORI,
    ROLE_TURISTAUTORIZZATI,
    ROLE_TURISTA,

}
